export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const GET_STATE_REQUEST = 'GET_STATE_REQUEST';
export const GET_STATE_REQUEST_SUCCESS = 'GET_STATE_REQUEST_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
